import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";

import { ThemeProvider } from "@/myComponents/ThemeContext"; // Import the ThemeProvider

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});
const notoSans = localFont({
  src: "./fonts/NotoSans-Regular.ttf",
  variable: "--font-noto-sans",
  weight: "400",
  style: "normal",
});

const valueSerif = localFont({
  src: "./fonts/ValueSerif-Bold.woff2",
  variable: "--font-value-serif",
  weight: "700",
  style: "normal",
});

const outfitRegular = localFont({
  src: "./fonts/Outfit-Regular.ttf",
  variable: "--font-outfit-regular",
  weight: "400",
  style: "normal",
});

const copernicusMedium = localFont({
  src: "./fonts/CopernicusTrial-Medium.ttf",
  variable: "--font-copernicus-medium",
  weight: "400",
  style: "normal",
});

const outfitLight = localFont({
  src: "./fonts/Outfit-ExtraLight.ttf",
  variable: "--font-outfit-extra-light",
  weight: "200",
  style: "normal",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${notoSans.variable} ${valueSerif.variable} ${outfitRegular.variable} ${copernicusMedium.variable} ${outfitLight.variable} antialiased`}
      >
        {/* Wrap children with ThemeProvider */}
        <ThemeProvider>
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
